### PR TITLE
new commits

### PR DESCRIPTION
**Pull request by KshshVrma**
added
same-tree 100
[->](https://leetcode.com/submissions/detail/803842022/)

symmetric tree 101
[->](https://leetcode.com/submissions/detail/803837894/
)
path sum 112
[->](https://leetcode.com/submissions/detail/809847376/)

path sum ii 113
[->](https://leetcode.com/submissions/detail/807215142/)

defanging an ip address 1108
[->](https://leetcode.com/submissions/detail/791753767/)

### CODE REVIEW

**Comment by code-chaser** [comment]
Hey @KshshVrma, can you please try submitting your solutions on LeetCode, and then share link to your submissions?
- Like this: https://leetcode.com/submissions/detail/813323575/
It will be easier to verify.

**Comment by KshshVrma** [comment]
links added

**Comment by code-chaser** [comment]
Nice, thanks for your contribution!
Keep going!

**Comment by code-chaser** [comment]
Solutions Verified ✅ 
Merging PR

**Pull request merged**
