### PR TITLE
5 new Java problems added

### PR DESCRIPTION
**Pull request by Baba-Yaga-1**
I have added the solutions of -
https://leetcode.com/problems/running-sum-of-1d-array/
https://leetcode.com/problems/sort-colors/
https://leetcode.com/problems/binary-search/
https://leetcode.com/problems/fibonacci-number/
https://leetcode.com/problems/power-of-two/

#44 

Can you check the PR?
I am a hacktoberfest contributor.

### CODE REVIEW

**Comment by code-chaser** [comment]
- Great Work!
- Just one thing, can you please rename your files to follow the `kebab-case` convention (words separated with a `-`, hyphen), I can merge it then

**Comment by code-chaser** [comment]
- Closes #44

**Comment by Baba-Yaga-1** [comment]
> * Great Work!
> * Just one thing, can you please rename your files to follow the `kebab-case` convention (words separated with a `-`, hyphen), I can merge it then

Okay, will do that.

**Comment by Baba-Yaga-1** [comment]
> * Great Work!
> 
>     * Just one thing, can you please rename your files to follow the `kebab-case` convention (words separated with a `-`, hyphen), I can merge it then

I have made the changes.

**Review by code-chaser — APPROVED** [review]
- Great!
- Merging PR! 🎉

**Pull request merged**
