### PR TITLE
 N-queens.py

### PR DESCRIPTION
**Pull request by avis011**
Backtracking solution of Leetcode question N-queens in pythin

### CODE REVIEW

**Comment by code-chaser** [comment]
Hey @avis011, can you link your submission? It would be easier to verify.
- Like this: https://leetcode.com/submissions/detail/813323575/
Thanks!

**Review by code-chaser — APPROVED** [review]
Solution manually verified ✅ 
Problem was quite difficult, so this PR counts as a significant contribution.
Merging PR 🎉

**Review by code-chaser — CHANGES_REQUESTED** [review]
- Oh, just one thing, can you please place your file in this folder https://github.com/code-chaser/leetcode-solutions/tree/main/src/python.
- And name it `n-queens.py`.

Thanks!

**Comment by avis011** [comment]
Everything you asked is done

**Comment by code-chaser** [comment]
- Closed with #31

**Pull request closed without merging**
