### PR TITLE
Java codes

### PR DESCRIPTION
**Pull request by Sabyasachi-Seal**
From Issue: https://github.com/code-chaser/leetcode-solutions/issues/58
And fixed Pull Request: https://github.com/code-chaser/leetcode-solutions/pull/61

### CODE REVIEW

**Comment by code-chaser** [comment]
Hey @Sabyasachi-Seal,
- First, I'm sorry, didn't notice you have mentioned a GFG problem in #58, I correct myself, only LeetCode solutions, please remove that GFG solution file;
- Second, please see #71 .

Thanks for your patience and sorry for the inconvenience.

**Comment by code-chaser** [comment]
You can fix it in this PR or open a new one, as you wish.

**Comment by Sabyasachi-Seal** [comment]
Hey @code-chaser , I have fixed whatever you had asked for. 
Do tell me if anymore changes are required.
Thanks :)

**Review by code-chaser — APPROVED** [review]
- Solutions manually verified ✅ 
- Merging PR

**Comment by code-chaser** [comment]
Closes #58

**Pull request merged**
