### PR TITLE
7 New Codes Added

### PR DESCRIPTION
**Pull request by KrishGaur1354**

### CODE REVIEW

**Comment by KrishGaur1354** [comment]
Also added Path-Sum-iii

**Comment by KrishGaur1354** [comment]
Added Rotate Image in Java

**Comment by KrishGaur1354** [comment]
I have now added 8 Files could you now Approve the PR and add `Hacktoberfest-Accepted` label

**Review by code-chaser — CHANGES_REQUESTED** [review]
- Everything's fine but you have deleted the `README.md`
- Can't merge

**Comment by KrishGaur1354** [comment]
> * Everything's fine but you have deleted the `README.md`
> * Can't merge

So do I have add it or not

**Comment by code-chaser** [comment]
@KrishGaur1354 do one thing:
- Save the files that you've added somewhere else.
- Delete your clone and create a fresh one from the original.
- Add your `.cpp`/`.java`/`.py` files and open a new PR

Sorry for the inconvenience but I can't merge this PR.
Thanks for your patience!

**Pull request closed without merging**
