### PR TITLE
Added 5 java Solutions of Leetcode Problem.

### PR DESCRIPTION
**Pull request by sakshimishra19**

### CODE REVIEW

**Comment by code-chaser** [comment]
Additionally, submit these solutions on LeetCode and share the submission links, it would be easier to verify.

**Comment by sakshimishra19** [comment]
Hey @code-chaser I have updated .

**Comment by code-chaser** [comment]
Sorry for the delay, let me check.

**Comment by code-chaser** [comment]
> Additionally, submit these solutions on LeetCode and share the submission links, it would be easier to verify.

Umm, this 😅 
Also, regarding the file naming thing, here:
- `decode_ways.java` -> `decode-ways.java`
- `design_Circular _Queue.java` -> `design-circular-queue.java`
- similarly for all the other files.

If you have any doubt you can ask.
Sorry for the inconvenience and thanks for your patience!

**Comment by sakshimishra19** [comment]
Hey @code-chaser sorry for the mistake I have changed it again..

**Review by code-chaser — APPROVED** [review]
- Great Work, @sakshimishra19 👍🏻 
- Submissions Verified ✅ 
- Merging PR 🎉

**Pull request merged**
